### ISSUE TITLE
Mapping Issues faced in Ranchi District

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#109]
While emitting the PAT1, PAT2, PAT3 and PAT4 data in Ranch District, they faced Mapping issue
While emitting the periodic assessment data to the emission directory, the emission process is happening but output files are not generated.  
Because there is mapping issue between the periodic_exam_mst, periodic_exam_qst_mst and periodic_exam result_trans table.
I checked periodic_exam_mst table columns name exam_id, exam_code,periodic_exam_qst_mst table columns name question_id and periodic_exam result_trans table columns name exam_id, question_id, exam_code mapping is not happening properly then I put properly and re emit the data.

**Comment by bommalla** [comment]
What- what is the issue faced?
While emitting the periodic assessment data to the emission directory, the emission process is happening but output files are not generated.  
Why- why it occurred (Root cause)?
Becuase there is mapping issue between the periodic_exam_mst, periodic_exam_qst_mst and periodic_exam result_trans table.
How - How to fix?
I checked periodic_exam_mst table columns name exam_id, exam_code,periodic_exam_qst_mst table columns name question_id and periodic_exam result_trans table columns name exam_id, question_id, exam_code mapping is not happening properly then I put properly and re emit the data.
