### ISSUE TITLE
Configuration of Report files and UI Properties

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#110]

**Comment by pandutibil** [comment]
What- what is the current reality, what is missing?
Currently, defined configurations which are based on the requirement cQube2.

Why- why the enhancement required?
In cQube 4.0 we are going to merge the capabilities of cQube 1 and cQube2, as a part of that in-order to support both the applications we need to enhance it.

How - How to do the enhancement?
By identifying all the configurable properties which are required for dynamic rendering of reports, UI elements and layout.

Who - who will make the enhancement?
UI team will be responsible for this enhancement.

when - when can finish the enhancement?
This will go along with the UI development because need to enhance this file if anything identified as a configurable in the UI development.
