### ISSUE TITLE
Telemetry, Composite and Progress card are not working in Jharkhand state

### ISSUE THREAD

**Issue by TLSravani** [Sunbird-cQube/community#137]

**Comment by bommalla** [comment]
What is the issue faced
Telemetry, Composite and Progress cards are not working in Jharkhand state.

why it is occured (Root Cause)
During the cQube installation Jharkhand people enabled all the data sources but they are using only PAT data source.That's why composite,progress card reports are not working.

How to fix it?
We are going to emit dependency datasources data one by one.Today we are successfully emit the teacher_attendance data

When can I fix the bug?
