### ISSUE TITLE
Cosmetic changes in azure installation(NVSK)

### ISSUE THREAD

**Issue by devu1454** [Sunbird-cQube/community#376]
1.if the access_type is national then Why should we fill the below config elements **(resolved)**

state_code: 
state_name:  
read_only_db_user: 
read_only_db_password:  
vpn_local_ipv4_address: 
proxy_host: 
keycloak_adm_user:  
keycloak_adm_passwd: 
report_viewer_config_otp:  
diksha_columns: 
static_datasource: 
management: 
session_timeout:   
theme:  
slab1: 
slab2:  
slab3:  
slab4:     

2.If the functionality is not implemented for cQube_4.0 then why we need to fill the below config elements(State)

Session_timeout:

3.If there is no option to choose the alternatives, then why it is in the config.yml file. **(resolved)**

map_name: leafletmap
auth_api: cqube

4.Order of error messages is not proper

**Comment by asifbasha61** [comment]
Modified the configuration variables according to state and national installations.
Validated the config file.

**Comment by asifbasha61** [comment]
Outcome: Validation error message should be in proper order according to the config.yml file.

**Comment by chetandg123** [comment]
@satendrapalsingh @asifbasha61  
Without Filling config.yml file and started the installation of cQube -> Config.yml file validation is not working 


![Image](https://user-images.githubusercontent.com/64146636/198953941-285afec5-69e3-4a31-9988-cc4c9bbc7d95.png)


Validating the config file...
Currently cQube 4.0 version is installed in this machine. Follow Upgradtion process if you want to upgrade.
If you re-run the installation, all data will be lost
Do you still want to re-run the installation (yes/no)? yes
Error - in system_user_name. Unable to get the value. Please check.
Error - in access_type. Unable to get the value. Please check.
Error - in mode_of_installation. Unable to get the value. Please check.
Error - in storage_type. Unable to get the value. Please check.
Checking for Postgres ...
WARNING: Postgres found.
Removing Postgres...

**Defect 1:** 
if user not filled up config.yml file then we are able see only 4 error messages , rest of variables error message should be displayed and installation process should be stopped instead of going to check for postgress task 
**Defect 2:** 
Error message should be shown in red color 


![Image](https://user-images.githubusercontent.com/64146636/198954532-480a98ea-0f7d-479a-85a5-0d31acb6db36.png)

**Comment by chetandg123** [comment]
@RNarmatha @ayesha-siddiq123  Re-tested the **4.Order of error messages is not proper** defect is resolved , able to see the error message as order of config variables
