### ISSUE TITLE
Explore Sunbird Obsrv (Dashlets, Report Service) and leverage it as much as possible

### ISSUE THREAD

**Issue by surendrasinghs** [Sunbird-cQube/community#90]
Please also study Sunbird Obsrv components such as Dashlets and Report Service. We should discuss if and how it can be leveraged in cQube

1. https://project-sunbird.atlassian.net/wiki/spaces/SBDES/pages/2312110137/Dashlets+Design+Doc
2. https://obsrv.sunbird.org/learn/product-and-developer-guide/report-service
3. https://project-sunbird.atlassian.net/wiki/spaces/SBDES/pages/3124363265/Access+to+Sunbird+datasets+via+APIs
4. https://project-sunbird.atlassian.net/wiki/spaces/SBDES/pages/865436288/Reports+Scale (refer to Report JSON Spec)

**Comment by pandutibil** [comment]
08-09-2022
I've gone through the implementation of Sunbird Dashlets where I observed that there are components for a leaflet map, chartjs reports, a big number for number metrics, and a data table for tabular information. Dashlet component requires three inputs i.e., the type of the report, options to be considered for the report like filters, data sets to be displayed in the report, etc., and data for the report.
While going through the above components I observed that filters can be included in each report. But if we need global filters for all the reports this option is not required. Also, I observed that existing dashlets were implemented in Angular 8, and then upgraded to Angular 9.And I tried to install the Dashlet package in the cQube Edu but got an error i.e., the package is not supported in the package because the dashlets were implemented in Angular 8, and then upgraded to Angular 9 and tried to include it in the cQube Edu which is developed in Angular 14. Then I had a call with Sharath Prasad and he suggested that I can upgrade the dashlets to Angular 14 by creating a fork from the root repository.

**Comment by pandutibil** [comment]
09-09-2022 & 10-09-2022
Worked on the upgradation of the sunbird Dashlets to Angular 14 which is latest version. And migration to Angular 14 is completed.

**Comment by pandutibil** [comment]
Gap analysis between requirements and the dashlet

- [ ] Markers are not present in the map report

- [ ] Drill down feature in the map report

- [ ] Interactive legend is missing in the map report

- [ ] Levels are missing at all the reports

- [ ] Upgrade the existing chart.js component to the new version

- [ ] APIs to be modified to support new dashlet reports

- [ ] Implement LO Table in the dashlet

**Comment by pandutibil** [comment]
After analysis on the sunbird dashlet and observed that it is suitable for cQube 4.0 but need to enhance the some of the capabilities of the dashlet. After discussions with the team and decided to integrate the dashlets in the cQube 4.0.

**Comment by RNarmatha** [comment]
Status is showing as Live.
